### ISSUE TITLE
Grants Menu

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#11]
A menu that shows pending grants from the wallet after tapping the "Grants" button:

<img width="363" alt="Screen Shot 2019-04-03 at 4 11 13 PM" src="https://user-images.githubusercontent.com/529104/55509929-1c4e8080-562b-11e9-8ce3-b236de56daa7.png">

Need reference to what's supposed to show (can't find design). I believe it was a drop-down in that area, but will likely have to be a modal in iOS

**Comment by jamesmudgett** [comment]
example of original:

![wallet](https://user-images.githubusercontent.com/318119/55899258-34695700-5b79-11e9-858d-a474c61f9aac.png)
