### ISSUE TITLE
Implement favicon fetching, caching, and database updates

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#116]
- [ ] Support favicon URLs which have been set to `clear` (`kClearFavicon`) during DB updates as seen here: [brave-core/publisher_info_database.cc#L279](https://github.com/brave/brave-core/blob/a0e854a10668d2c55c7644f6d4149c79744102dc/components/brave_rewards/browser/publisher_info_database.cc#L279)
- [ ] Implement `fetchFavicon` LedgerClient method which fetches a favicon based on the website URL (i.e. `https://duckduckgo.com`) and calls back with the favicon URL (i.e. `https://duckduckgo.com/favicon.ico`).  This will be forwarded to brave-ios through brave-rewards-ios to find the favicon, download it, and cache it. ([brave-core/rewards_service_impl.cc#L2002](https://github.com/brave/brave-core/blob/a0e854a10668d2c55c7644f6d4149c79744102dc/components/brave_rewards/browser/rewards_service_impl.cc#L2002))

**Comment by iccub** [comment]
Temporary solution is to fetch favicons on clinet side(brave-ios) by publisher url, see for example here https://github.com/brave/brave-rewards-ios/pull/115
