### ISSUE TITLE
"Tip this site monthly" action in publishers summary

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#12]
These elements are much too small and likely will have to expand to be taller and also show option chooser in a modal (unless that down-arrow is a mistake)

Design reference:

<img width="835" alt="Screen Shot 2019-04-03 at 4 13 38 PM" src="https://user-images.githubusercontent.com/529104/55510089-718a9200-562b-11e9-9c52-a082cdf2d6c8.png">

**Comment by jamesmudgett** [comment]
The original design calls for this to expand accordion style. We could bypass this and go with a push on vc to show in a tableview. Can rotate the arrow -90 degrees.

**Comment by kylehickinson** [comment]
Is there a reference to what that design looks like on desktop when it was expanded, or can you point me to a Sketch file that has it? :)

**Comment by kylehickinson** [comment]
Oh, it looks like these comments were meant for #11, this ticket is about the "Tip this site monthly" under the "Include in auto-contribute" switch

**Comment by jamesmudgett** [comment]
@kylehickinson good catch, thanks. The one on right is correct (left is an older version). The text and icon should be a single button, we may need to create more space from toggle.

**Comment by kylehickinson** [comment]
What does this look like when you click on the "5 BAT 🔽"? Does it bring up a similar dropdown as #3 ?

**Comment by kylehickinson** [comment]
Solution: clicking on brings up BAT selector same as auto-contribute settings

**Comment by kylehickinson** [comment]
Fixed by #76
