### ISSUE TITLE
isNotificationsAvailable should return true based on the visible screen on the app

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#156]
Ads should only show when the user is browsing, meaning if they are in settings, bookmarks, etc. it will return false

(Should check the top level window for full-screen video players)

**Comment by kylehickinson** [comment]
@tmancey We have a requirement to not show the ads unless the user has the main browser visible (i.e. not blocked by full-screen modals such as Bookmarks, Settings, etc.)

Do we want to return false in these cases, or just queue up ads on our side and show them once the user dismisses these full-screen modals?

**Comment by tmancey** [comment]
@kylehickinson Please return false, thanks
