### ISSUE TITLE
Rewards Onboarding UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#159]
## Description
Add Brave Rewards to the onboarding experience for iOS.
Product spec: https://docs.google.com/document/d/15ouI4hsKOduE3IrB-RkvPaPww_iqnc6MLmvSqoCu6Os/edit#

#### iPhone
The Shields screen now has a "Continue" button that takes the user to the next screen in onboarding.

![ios 2](https://user-images.githubusercontent.com/2388823/64814501-6c296000-d558-11e9-95bb-1ecf581bcf7c.png)
![ios 3](https://user-images.githubusercontent.com/2388823/64813917-523b4d80-d557-11e9-97cd-6ef8c20c574b.png)

The "Agree" button is disabled until the user checks the Terms checkbox.

![ios 4](https://user-images.githubusercontent.com/2388823/64813918-523b4d80-d557-11e9-94e9-b8cc677ad40f.png)

Tapping on the link to Terms displays our terms page in webview.

![ios 5 - terms](https://user-images.githubusercontent.com/2388823/64815421-66cd1500-d55a-11e9-9191-945c0bd46620.png)

The "Agree" button is enabled once the checkbox is checked.

![ios 5](https://user-images.githubusercontent.com/2388823/64813943-5cf5e280-d557-11e9-96ec-a9c41597becc.png)

After the user taps "Agree", trigger ads onboarding with a count down timer.
Gradient values:
start #4F30AB
middle #FF1893
end #FA7250

![ios 6](https://user-images.githubusercontent.com/2388823/64816108-e0b1ce00-d55b-11e9-9822-8b3e04bed305.png)

Show our custom notification (product spec: https://docs.google.com/document/d/1l_jXRt5o_RKBFiv3y3RHivrt5xGxSpzua-0OjTPc5I4/edit?ts=5d5d7079)

![ios 7](https://user-images.githubusercontent.com/2388823/64813945-5cf5e280-d557-11e9-8499-d5f0dfcc2765.png)

If the user taps the notification, show https://brave.com/my-first-ad/

![ios 10](https://user-images.githubusercontent.com/2388823/64813969-697a3b00-d557-11e9-9563-a14bd8712bef.png)

If the user ignores the notification, show a start browsing screen.

![ios 8](https://user-images.githubusercontent.com/2388823/65282102-f50c4280-dae8-11e9-8e2f-ee67005a4f58.png)

#### iPad
iPad designs are identical to iPhone, but displayed as a card on top of a gradient background.

![12 9″ iPad Pro - screen 2](https://user-images.githubusercontent.com/2388823/64815602-ccb99c80-d55a-11e9-942d-a6ff0467f24e.png)
![12 9″ iPad Pro - screen 3](https://user-images.githubusercontent.com/2388823/64814035-857ddc80-d557-11e9-85bd-6c6b7ced0c46.png)
![12 9″ iPad Pro - screen 4](https://user-images.githubusercontent.com/2388823/64814036-857ddc80-d557-11e9-9b39-4f811c360cca.png)
![12 9″ iPad Pro - screen 5](https://user-images.githubusercontent.com/2388823/64814037-86167300-d557-11e9-96ba-a98bb0992b92.png)
![12 9″ iPad Pro - screen 6](https://user-images.githubusercontent.com/2388823/64816121-e7404580-d55b-11e9-842c-ea6ec43eb578.png)
![12 9″ iPad Pro - screen 8](https://user-images.githubusercontent.com/2388823/65282259-53392580-dae9-11e9-8655-c48b284b9bcf.png)

#### Dark Mode
![dark mode 1](https://user-images.githubusercontent.com/2388823/64820073-85d0a480-d564-11e9-879a-d337d0589479.png)
![dark mode 3](https://user-images.githubusercontent.com/2388823/64820074-86693b00-d564-11e9-9151-997c71b83c1a.png)
![dark mode 4](https://user-images.githubusercontent.com/2388823/64820075-86693b00-d564-11e9-899a-01777d0cd86d.png)
![dark mode 5](https://user-images.githubusercontent.com/2388823/65283444-00ad3880-daec-11e9-923d-2c5b50cca8ee.png)

#### Animated transitions between screens
When the white panel changes heights between screens, the height change and content should be animated for a smooth transition, for example (this is on Android; in iOS we would maintain the rounded corners of the white panel):
![welcome transition out](https://user-images.githubusercontent.com/2388823/61094617-cac14900-a404-11e9-8fd8-f49115b14d2f.gif)

![slide transition](https://user-images.githubusercontent.com/2388823/61094387-d4967c80-a403-11e9-81e9-b9e6ee083f4a.gif)

higher res video versions:
[general transition.zip](https://github.com/brave/browser-android-tabs/files/3384480/general.transition.zip)

**Animation breakdown:** the content in the white panel fades out: start Opacity: 1, end Opacity: 1, duration 0.2s. The white bg resizes starting at T=0.1s to the appropriate height for the next screen, duration 0.3s.  The illustration and new text content fades in starting at T=0.3s: start Opacity: 0, end Opacity: 1, duration: 0.4s.

### New user, In ad region
Show search engine selection, Brave Shields explanation, Brave Rewards opt-in with Terms of Service, and ad onboarding.

![user flow - ios onboarding ads available](https://user-images.githubusercontent.com/2388823/65283543-34885e00-daec-11e9-9b82-ce30e6af9140.png)

### New user, Out of ad region
Show search engine selection, Brave Shields explanation, and Brave Rewards opt-in with Terms of Service.

![user flow - ios onboarding ads unavailable](https://user-images.githubusercontent.com/2388823/65283570-3fdb8980-daec-11e9-8e92-d38a31052d66.png)

For this user segment, the text on the Brave Rewards should not mention ads: 

> Support your favorite websites and creators based on your attention.

![ios ads unavailable](https://user-images.githubusercontent.com/2388823/64814329-15238b00-d558-11e9-9301-37bf705c4e45.png)

### Existing user, Brave Rewards OFF
Show Brave Rewards opt-in with Terms of Service, and ad onboarding.

![user flow - ios onboarding BR off](https://user-images.githubusercontent.com/2388823/65283624-5550b380-daec-11e9-9967-631741f28dd6.png)

### Existing user, Brave Rewards ON
Show ads opt-in with ad onboarding.

![user flow - ios onboarding BR on](https://user-images.githubusercontent.com/2388823/65283638-5da8ee80-daec-11e9-9d8a-6d70c055863d.png)

![ios br on](https://user-images.githubusercontent.com/2388823/64899986-01a11e80-d643-11e9-9b60-7eaa7ccdbddb.png)

## Assets
[png assets.zip](https://github.com/brave/brave-rewards-ios/files/3607975/png.assets.zip)

Lottie assets:

- Rewards: https://assets10.lottiefiles.com/packages/lf20_uX7EQp.json
Preview: https://lottiefiles.com/share/uX7EQp
- Ad notification: https://assets5.lottiefiles.com/packages/lf20_CawP3d.json
Preview: https://lottiefiles.com/share/CawP3d

Abstract link for more CSS and plain text: https://share.goabstract.com/382f3231-c578-468e-8be6-fca295b7fd79?sha=65d9fd8a0b273c12a47465c32e75c865c914954b

**Comment by tmancey** [comment]
Blocked as we should wait for phase 1 in iOS 13 build otherwise, there could be possible rebasing. If we run low on tickets or another developer is available then this work could be started

**Comment by karenkliu** [comment]
@kylehickinson @Brandon-T design specs and Lottie files added!

**Comment by tmancey** [comment]
Blocked as need to discuss flow if ads are not available in a specific region
