### ISSUE TITLE
Hide Brave Rewards Icon 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-rewards-ios#203]
In Settings, under OTHER SETTINGS, Sync, Brave Rewards, add a section called Display & Appearance 

Here add the following: 

Hide Brave Regards Icon 
(sub text) Hides the Brave Rewards icon when Brave Rewards is not enabled 

Toggle Switch On | Off 
Default off

(see Android for formatting) 

The option should be grey'ed out if Brave Rewards is enabled 

Also, 
Move Show Bookmark Shortcut into Display & Appearance and place it above Hide Brave Regards Icon 

i.e.

Display & Appearance

   Show Bookmark Shortcut
   Hide Brave Regards Icon

**Comment by kylehickinson** [comment]
Please add a screenshot of Android implementation

**Comment by anthonypkeane** [comment]
**UPDATE**

In Settings > Display & Brightness add the following under Display & Brightness 

Show Bookmarks Shortcut  (https://github.com/brave/brave-ios/issues/1391)
_ Just move in here_ 

Hide Brave Regards Icon
(sub text) Hides the Brave Rewards icon when Brave Rewards is not enabled

Toggle Switch On | Off
Default off

@jamesmudgett can you please confirm?

**Comment by kylehickinson** [comment]
@anthonypkeane 

You want the `Show Bookmarks Shortcut` put inside the Display & Brightness menu?

<img width="384" alt="image" src="https://user-images.githubusercontent.com/529104/65178916-cbd7ad80-da27-11e9-90c7-ee050d903c0d.png">

**Comment by anthonypkeane** [comment]
Confirming


Settings
    General
    
    Display
        Brightness 
        Show Tabs Bar
        Show Bookmarks Shortcut
        Hide Brave Rewards Icon


Brightness = the Automatic/Light/Dark options

**Comment by jhreis** [comment]
Maybe we should follow Apple and call it "Appearance" instead of "brightness". Will almost certainly be weird if we diverge our brightness meaning from what iOS uses.

**Comment by anthonypkeane** [comment]
Appearance sounds fine with me
