### ISSUE TITLE
Notifications Badge Missing on Brave Rewards panel icon

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#208]
When the user has a notification/alert in their wallet, the badge doesn't show up on the Brave Rewards icon

Implementation to be done in brave-ios, and I believe is partially complete. Just needs UI for badge number

*Final Decision/Expected Result*: 

1. For MVP we will be doing only a red dot, no number. 
2. Notification Badge takes visible priority over verified publisher state. If the user has a notification a red dot appears. If the user is visiting a verified publisher site, the purple checkmark appears. If the user has both notifications and is visiting a verified publisher, the red dot appears.

**Comment by kylehickinson** [comment]
@anthonypkeane Is there logic around what to show if the user has notifications while visiting a verified publisher? I assume verified publisher badge takes precedence but would be good to confirm.

**Comment by anthonypkeane** [comment]
Details here: https://app.goabstract.com/projects/1ba67860-79bb-11e8-8738-c75a805f73cf/branches/master/commits/8b16b0c024db89f45d908b6e915345b0b2987b68/files/C26ACA3E-7AC8-440E-9975-6ECD4BDB1B0F/layers/F1AF0090-8825-4744-B32A-AC859E28470A?commentId=f0e11b22-16aa-42e4-be49-5842424f0554

**Comment by kylehickinson** [comment]
@anthonypkeane I thought we decided in Slack that we aren't putting numbers? Our shields icon doesn't show any badge number either (we also have more things in our URL bar than android)
