### ISSUE TITLE
Add payment id to brave://rewards-internals to help support with testing

### ISSUE THREAD

**Issue by tmancey** [brave/brave-rewards-ios#236]
Add payment id to brave://rewards-internals to help support with testing

**Comment by kylehickinson** [comment]
So we don't have a `brave://` url scheme style settings the same way as desktop. Perhaps we can add a special `brave://rewards-internals` check to the URL and if it is, we display a native VC with the info?

**Comment by tmancey** [comment]
Or we just access from the about screen, @anthonypkeane @alexwykoff your thoughts?

**Comment by kylehickinson** [comment]
We don't have an about screen :) Currently clicking on the Version number in the About section in shows a copy version number sheet.

**Comment by tmancey** [comment]
could make sense to just add to the about section also with a copy sheet

**Comment by kylehickinson** [comment]
Yeah that could work too, do we care about all the rewards internal info? (Key Info Seed validity, Persona ID, User ID, Wallet creation date)

**Comment by tmancey** [comment]
@NejcZdovc Your thoughts please?

**Comment by NejcZdovc** [comment]
I would go in native VC way as I see that we will be adding more data to that page and would be good that all platforms are in sync on what we display. This way QA always has the same data

**Comment by NejcZdovc** [comment]
this is what we have on desktop

![image](https://user-images.githubusercontent.com/9574457/66168287-bd75be00-e5f1-11e9-9e44-a70e6676ac26.png)

**Comment by anthonypkeane** [comment]
I suggest we put this in iOS Settings > Brave > Brave Rewards

 `Brave Reward`s would be a new section within that setting

**Comment by kylehickinson** [comment]
@anthonypkeane As I mentioned in Slack, this wouldn't work well for support. The user cannot copy/paste any of the info, the section/settings would have to be visible regardless of if the user has rewards enabled, and also the only way to get that data in there is to write it to UserDefaults, they can't be read and updated on the fly, meaning it's possible for the data to be out of date

**Comment by anthonypkeane** [comment]
Issue moved to [brave/brave-ios #1643](https://github.com/brave/brave-ios/issues/1643) via [**ZenHub**](https://www.zenhub.com/)
