### ISSUE TITLE
Add empty balance report UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#37]
On WalletViewController there is a state where the `contentView` is actually showing "No activities yet" as seen in this desktop ref:

<img width="374" alt="empty" src="https://user-images.githubusercontent.com/529104/57701233-92ca9f00-7629-11e9-9e18-f9dddda6e9cb.png">

I assume this will be shown when all items in balance report are 0

**Comment by iccub** [comment]
Another variation: when you have some BAT, but have not earned anything lately.
This view should still be able to show the disclaimer box with pending unverified contributions

<img width="378" alt="Zrzut ekranu 2019-05-15 o 17 07 35" src="https://user-images.githubusercontent.com/6950387/57786548-f3de9980-7733-11e9-970b-4ebada347d87.png">

**Comment by kylehickinson** [comment]
So it looks like this might be fairly easy to setup then :) 

We'll just have to check whether or not `rowViews` is empty, and if it is, add a `UIView` containing a centred `UILabel` inside the stack view, since the rest should be the same as the normal layout. I think it'll have to be done in both places since protocol won't be able to manage the different view structures
