### ISSUE TITLE
Integrate Tips Detail & List

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#48]
In settings, in the tips section, you can tap the View Details button. On this new screen, we should:

- [x] Total tips this month value should be computed correctly
- [x] Combine two data points: one-time tips (`listOneTimeTips:`), recurring tips (`listRecurringTips:`) and 
- [x] Media publishers may show a name + `on YouTube`/`on Twitch` instead of domain
- [x] Recurring Tips are editable by swipe-to-"remove" (cancelling the recurring payment)
- [x] Recurring Tips subtitle is "Recurring"
- [x] One-Time Tips subtitle is "One time" and shows a date next to it
- [ ] If the user has any recurring tips, a new cell appears that looks the same as Auto-Contribute/Ads details where it shows the next monthly payment date

![Simulator Screen Shot - iPhone X - 2019-05-15 at 17 00 58](https://user-images.githubusercontent.com/529104/57809229-099f8f00-7733-11e9-9b97-5ac4b73215b0.png)

Desktop ref: https://brave.github.io/brave-ui/?path=/story/feature-components-rewards-table--donation

**Comment by danishjafri88** [comment]
@kylehickinson should the list be sorted by date or type?

**Comment by kylehickinson** [comment]
@danishjafri88 Date
