### ISSUE TITLE
Handle no internet and slow internet negative flows

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#53]
When you launch the app, there are a number of API calls that must be made to make sure you have up to date data: 

- Publishers List
- Wallet Balance / Rates
- Wallet Properties

We need to determine how to handle these negative flows:

- User has no internet connection
- User has an extremely slow internet connection

###  _"User has no internet connection"_ options

- Show some sort of disclaimer saying their balance/data may be out of date
- Disable access to the rewards panel (however, we won't know they dont have internet connection until we try to make a call to update the data). Greyed out button (same as private mode BR button)?

###  _"User has an extremely slow internet connection"_ options

- Full panel blocked by a loader until _required data*_ needed has been collected (* - balance + wallet properties). Obviously not as nice, but hopefully won't be seen that often unless user accesses the panel before the data has been updated
- Add a loader next to the balance while its updating indicating that the shown data may not be up to date
  - **Potential caveats**: 
      - The user still has access to the panels settings, if they were to move to settings before getting BAT → USD rates, we wouldn't be able to show rates.
      - If we cache old data and show said old data, we would need to be able to indicate that said data may not be correct/out of date if the user is given freedom to use the panel with out-of-date data
      - What if your balance has not been updated and you go to tip someone? We would obviously need to block tipping while your balance is not up to date

**Comment by EyanGoldman** [comment]
How do we handle tipping in an extremely slow internet connection? Does the wallet balance/rates need to be updated before a user is able to attempt to send a tip? If not, would it be possible for someone to see BAT they no longer have and try to spend it? If this is the case, we may not want to show anything while loading in and just replace it with a loader to avoid this

**Comment by EyanGoldman** [comment]
Looked at desktop and android, and this would be my suggestion. We do nothing for slow connection, and use an iOS compatible version of the attached banner (for both the panel and settings page) for no internet. @alexwykoff can confirm. 
![Screen Shot 2019-07-29 at 1 08 58 PM](https://user-images.githubusercontent.com/8962135/62559150-414c3d80-b82f-11e9-9f65-eb01ac0aecb6.png)

**Comment by jsecretan** [comment]
This sounds good to us @EyanGoldman
