### ISSUE TITLE
Create a PublisherInfo when inserting/updating other entities which have a relationship to PublisherInfo

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#55]
We have many side tables that have a one-way relationship back to a publisher, however `BATLedgerDatabase` lets you create any of these entities without requiring its corresponding publisher to exist.

We should create a relating PublisherInfo object if one does not already exist (or assert)

**Comment by iccub** [comment]
After investigation it seems that we match the behavior on brave-core. They do not check for publisher when inserting children objects
