### ISSUE TITLE
Wallet Detail Monthly Statements

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-rewards-ios#6]
There's a monthly statements button shown in design, but needs info of where this goes in mobile (Settings > Wallet Details?). 

Also needs info on tapping it, does it go to a web page, are we displaying something in app, etc.

![wallet](https://user-images.githubusercontent.com/529104/55507617-068a8c80-5626-11e9-93e8-574c60bff1a1.png)

**Comment by anthonypkeane** [comment]
@jenn-rhim can you provide the details on this one please?

**Comment by anthonypkeane** [comment]
Hey @jamesmudgett can you get the info from @jenn-rhim on this

**Comment by kylehickinson** [comment]
Not happening on mobile atm

**Comment by tmancey** [comment]
Duplicate of #135
